version: "3"
services:
  php:
    container_name: ledsystem-php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      args:
        user: ${USER}
        uuid: ${UID}
        group: ${GROUP}
        guid: ${GID}
    environment:
      - APPROOT=/application
    image: ledsystem/php:latest
    env_file: .env
    working_dir: /application
    depends_on:
      - db
    volumes:
      - .:/application
      - ./docker/php/settings.ini:/usr/local/etc/php/conf.d/settings.ini
      - ./docker/php/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    networks:
      ledsystem:
        ipv4_address: 10.14.0.4

  nginx:
    container_name: ledsystem-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      ledsystem:
        ipv4_address: 10.14.0.3

  db:
    container_name: ledsystem-mysql
    image: mysql
    volumes:
      - ledsystem_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ledsystem
      - MYSQL_HOST=127.0.0.1
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      ledsystem:
        ipv4_address: 10.14.0.5

volumes:
  ledsystem_db:

networks:
  ledsystem:
    external: true
